{% set version = "1.20.2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-getopt
  version: {{ version|replace("-", "_") }}

source:
  fn: getopt_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/getopt_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/getopt/getopt_{{ version }}.tar.gz


  sha256: 3d6c12d32d6cd4b2909be626e570e158b3ed960e4739510e3a251e7f172de38e

build:
  noarch: generic
  number: 2001


  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('getopt')"  # [not win]
    - "\"%R%\" -e \"library('getopt')\""  # [win]



about:
  home: https://github.com/trevorld/getopt
  license: GPL (>= 2)
  summary: Package designed to be used with Rscript to write ``#!'' shebang scripts that accept
    short and long flags/options. Many users will prefer using instead the packages
    optparse or argparse which add extra features like automatically generated help
    option and usage, support for default values, positional argument support, etc.
  license_family: GPL3



extra:
  recipe-maintainers:
    - dpryan79
    - croth1
