travis:
  secure:
    BINSTAR_TOKEN: dXj/bNYMkUeLLNtYB7rvKidY7v0NCKUxQcpx+cv1e1yhkC86J/nu/5hKtiHbP3tPcxG+e4VLps7+VcR4kINgoGB+zy8Xtj0ubBcW1UkIFW0G27kgYeM8+ip6TkPY8qO4kiD8aYufaVl84+padmZGQa9fphoo7Q2aYq0Was2rgVmMrBthoEvBlC9CeKGOk7cJVeLFLb+v9KnUSAaOpuJG2b6BFR9btW6+Sfo9UMQm0xV9XWe3n+rLvFiz5QaRCzLQsRUPysnhEzsV3OfBrdfqIOwbGBuPu/0PrEugly0c31kHWih5FtezDRwnaWTVQgeD+qe73+DGQATfoewPCeaA94BGvE7oD1jJSWb+OF29HdAwqLrcv/xjVGP3l5RQKJFXBB5Q+Wlqw+ffAlIqpZ6N6Q2nXUW8w8vzwmdVjGwuO6loVYHcfaEtM8S2wdxKQCtVbLwUX+oWJHASOPKGRyVKFQ3F9MfJkGjOkNp3q8ngSNL8wAAB+mohAQfzs+zvxX2O9HnKro0qOl81aESRQypHtG0T/d27jvpTxlt12qnQYp/wv+L1iuvhFmCDYvSVdf8W5kIoUwxf+nGUe3vX4Ysnh5SUyG3wiU4awMb9gEKBuYQGIGCTWa5KiPx8BJZNLTe/RPlN6YysCT6cWsP+EOWndlCQY78E3mdhGcNHzhHYh/Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
